server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  artemis:
    user: admin
    password: admin
    broker-url: tcp://localhost:5672
    embedded:
      enabled: false
    pool:
      enabled: true
      max-connections: 10
  jms:
    template:
      receive-timeout: 5000ms

tomcat:
  ajp:
    port: 8099

general:
  message-schema:
    version:
      current: 9
      available:
        8: fi.uta.ristiinopiskelu.messaging.message.v8.MessageType
        9: fi.uta.ristiinopiskelu.messaging.message.current.MessageType
  elasticsearch:
    embedded: true
    hosts: localhost
    clusterName: ripa-cluster
    username:
    password:
    caCertificatePath: 

ristiinopiskelupalvelu:
  hakaLogoutUrl: http://www.disney.com
  activemq:
    queueName: handler
