server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  artemis:
    user: ${activemq_admin_ui_username}
    password: ${activemq_admin_ui_password}
    broker-url: ${activemq_hosts}
    embedded:
      enabled: false
    pool:
      enabled: true
      max-connections: 10
  jms:
    template:
      receive-timeout: 5000ms

tomcat:
  ajp:
    port: 8099

general:
  elasticsearch:
    embedded: true
    hosts: ${elasticsearch_hosts}
    clusterName: ripa-cluster
    username: ${elasticsearch_username}
    password: ${elasticsearch_password}
    caCertificatePath: ${elasticsearch_cacertificatepath}
