server:
  port: 8080
  servlet:
    context-path: /handler
    session:
      timeout: 1800s
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  artemis:
    admin-ui-user: ${activemq_admin_ui_username}
    user: ${activemq_username}
    password: ${activemq_password}
    broker-url: ${activemq_hosts}
    embedded:
      enabled: false
    pool:
      enabled: true
      max-connections: 10
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
springdoc:
  api-docs:
    groups:
      enabled: true
camel:
  springboot:
    main-run-controller: true
    stream-caching-enabled: true
general:
  messageSchema:
    version: 9
  camel:
    route:
      base:
        max-threads: 10
      acknowledgement:
        max-threads: 10
        send: direct:sendAcknowledgement
      network:
        max-threads: 10
        create: direct:createNetwork
        delete: direct:deleteNetwork
        update: direct:updateNetwork
      courseunit:
        max-threads: 10
        create: direct:createCourseUnit
        delete: direct:deleteCourseUnit
        update: direct:updateCourseUnit
      studymodule:
        max-threads: 10
        create: direct:createStudyModule
        delete: direct:deleteStudyModule
        update: direct:updateStudyModule
      registration:
        max-threads: 10
        request: direct:registrationRequest
        reply: direct:registrationReply
      realisation:
        max-threads: 10
        create: direct:createRealisation
        delete: direct:deleteRealisation
        update: direct:updateRealisation
      studyrecord:
        max-threads: 10
        create: direct:createStudyRecord
        reply: direct:studyRecordReply
      student:
        max-threads: 10
        update: direct:updateStudent
        update_reply: direct:updateStudentReply
        update_studyright: direct:updateStudentStudyRight
        update_studyright_reply: direct:updateStudentStudyRightReply
  activemq:
    queue: jms:queue:handler
  elasticsearch:
    hosts: ${elasticsearch_hosts}
    clusterName: ripa-cluster
    username: ${elasticsearch_username}
    password: ${elasticsearch_password}
    caCertificatePath: ${elasticsearch_cacertificatepath}
