spring:
  artemis:
    user: ${activemq_username}
    password: ${activemq_password}
    broker-url: ${activemq_hosts}
    embedded:
      enabled: false
    pool:
      enabled: true
      max-connections: 10
  jms:
    template:
      receive-timeout: 10000ms

simplejavamail:
  smtp:
    host: ${smtp_host}
    port: ${smtp_port}

general:
  message-schema:
    version:
      current: 9
      available:
        8: fi.uta.ristiinopiskelu.messaging.message.v8.MessageType
        9: fi.uta.ristiinopiskelu.messaging.message.current.MessageType
  elasticsearch:
    hosts: ${elasticsearch_hosts}
    clusterName: ripa-cluster
    username: ${elasticsearch_username}
    password: ${elasticsearch_password}
    caCertificatePath: ${elasticsearch_cacertificatepath}
  activemq:
    environment: ${activemq_environment}
    dlq-queue-pattern: jms:queue:%s.DLQ
  email:
    address:
      administrator: ${administrator_email_address}
      noreply: ${noreply_address}
      subject: "Ristiinopiskelupalvelussa häiriö viestienkäsittelyssä"
      body: |
        Tämä on automaattinen viesti johtuen Ristiinopiskelupalvelussa tapahtuneesta viestienkäsittelyn häiriöstä.
        Organisaationne viestijonossa on ollut viesti tai viestejä, joiden käsittely on toistuvasti epäonnistunut.
        Nämä viestit on poistettu viestijonosta, jotta ne eivät tuki järjestelmää kokonaan. Viestit ovat kuitenkin
        tallessa Ristiinopiskelupalvelun palvelimella, josta ne voidaan tarvittaessa noutaa ja käsitellä
        manuaalisesti. 

        Ristiinopiskelupalvelun ylläpito auttaa itse vian määrityksessä sekä tarvittaessa viestien noudossa,
        ristiinopiskelupalvelu@postit.csc.fi. Vian määrittämiseen saatetaan myös tarvita apua organisaationne
        palvelinylläpidolta sekä perusjärjestelmän toimittajalta.

        Ympäristö: %s

        Alla niiden viestien lukumäärät ja viestityypit, joiden käsittely on epäonnistunut:
        
        %s

        Terveisin,

        Ristiinopiskelupalvelun ylläpito
  camel:
    redeliveryDelay: 4500 # in milliseconds
    redeliveryErrorLoggingDelay: 30000 # in milliseconds
  emailsender:
    enabled: true
    pollingRate: "0 */15 * * * *"
